name = "RHD - LifeCore"
prefix = "rhd"

[version]
major = 2
minor = 1
patch = 0

[hemtt.build]

[hemtt.release]
archive_name = "RHD-LifeCore-{version}"

[properties]
author = "LT. Toad"

[files]
exclude = [
    "addons/*/README.md",
    "addons/*/version.hpp",
]
