/*
    RHD - LifeCore | Antistasi Ultimate Base Bridge
    Author: LT. Toad
    ---------------------------------------------------------------------------
    RHD is a Life RP layer on top of the Antistasi Ultimate campaign core.

    The installed A3A campaign owns strategic world state. This bridge waits for
    its server initialization and then exposes a clean RHD-facing state layer.

    BEGINNER EDITORS:
    Do not edit this file for normal gameplay setup.
    Edit `core/fn_init.sqf` for RHD settings and use Eden for map layout.
    ---------------------------------------------------------------------------
*/

if (!isServer) exitWith {false};

private _timeout = time + 180;

// Wait for Antistasi Ultimate to finish its own server initialization.
waitUntil {
    sleep 0.5;
    (!isNil "serverInitDone" && {serverInitDone}) || {time > _timeout}
};

// The public A3A function namespace is our hard runtime check.
private _hasA3A = !isNil "A3A_fnc_initServer";

if (!_hasA3A || {!serverInitDone}) exitWith {
    diag_log "[RHD-LIFECORE] ERROR: Antistasi Ultimate was not detected or did not finish startup.";
    missionNamespace setVariable ["RHD_A3A_BASE_READY", false, true];
    false
};

missionNamespace setVariable ["RHD_A3A_BASE_READY", true, true];
missionNamespace setVariable [
    "RHD_A3A_BASE_VERSION",
    missionNamespace getVariable ["A3A_serverVersion", "unknown"],
    true
];
missionNamespace setVariable ["RHD_A3A_BASE_STARTED", true, true];
missionNamespace setVariable ["RHD_A3A_ZONE_MARKERS", [], true];
missionNamespace setVariable [
    "RHD_A3A_HQ",
    if (isNil "petros") then {objNull} else {petros},
    true
];

// Build one readable list for the RHD tablet / admin systems.
[] spawn {
    private _deadline = time + 30;

    waitUntil {
        sleep 1;
        (!isNil "controlsX") || {time > _deadline}
    };

    private _markers = [];

    if (!isNil "controlsX") then {
        _markers append (controlsX select {
            _x isEqualType "" && {_x in allMapMarkers}
        });
    };

    _markers append (allMapMarkers select {
        (_x find "rhd_zone_") isEqualTo 0
    });

    _markers = _markers arrayIntersect _markers;
    missionNamespace setVariable ["RHD_A3A_ZONE_MARKERS", _markers, true];
};

true
